### ISSUE TITLE
Calorie calculator nitpicks

### ISSUE THREAD

**Issue by dondido** [syber83/Calorie-calculator#1]
1. No closing body tag
2. Using `<br>` can be avoided and css styling can be used instead
3. Definition list can be used when listining food items
4. It is considered a good practise to use class names instead of ids for css selectors
5. Css formatting can be improved
6. Variable caloriesDisplay can be moved one level up so DOM traversal happens only once

**Comment by syber83** [comment]
Cheers!

**Comment by dondido** [comment]
Lovely bubbly, keep up the good work!

**Comment by syber83** [comment]
Thanks alot!
